title: <p align="center"> Platon Makinen </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  Espoo, Finland
  <br> (+358) 40 623 5008
  <br> makinenplaton@gmail.com
  <br> <a href="pdf/Carbone_Giorgio_CV_eng.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/platon-makinen-b1b190212/">LinkedIn</a> |
  <a href="https://github.com/degazzz">GitHub</a> 
  </p>
  
  <p align="justify">
  I am an aspiring <b>data scientist</b> who enjoys connecting the dots by the use of technology. 
  <br><br>
  I am pursing <b>Bachelor's Degree in Data Science at Aalto University</b>, where I’m receiving solid training in all the major fields of Data Science and Machine Learning
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID


